package com.vigil.wear.metrics

import com.vigil.wear.session.SessionMetricsSnapshot

object MetricCatalog {
    fun fromSnapshot(
        snapshot: SessionMetricsSnapshot,
        sensorSdk: ProviderAvailability,
        androidSensors: ProviderAvailability,
        healthServices: ProviderAvailability,
    ): List<MetricReading> {
        return listOf(
            MetricReading(
                metricId = "heart_rate",
                title = "Heart rate",
                provider = MetricProvider.SensorSdk,
                serviceName = "Sensor SDK",
                sourceKey = "HEART_RATE_CONTINUOUS",
                kind = MetricKind.Raw,
                value = snapshot.heartRateBpm?.toString() ?: "--",
                unit = "bpm",
                status = numericStatus(snapshot.heartRateBpm?.toFloat(), 55f, 145f),
                classifierContribution = "Effort/rest discriminator",
                availability = sensorSdk.message,
                permissionState = sensorSdk.permissionState,
                supportState = sensorSdk.supportState,
            ),
            MetricReading(
                metricId = "hrv",
                title = "HRV (RMSSD)",
                provider = MetricProvider.SensorSdk,
                serviceName = "Sensor SDK",
                sourceKey = "HEART_RATE_CONTINUOUS · IBI",
                kind = MetricKind.Derived,
                value = snapshot.hrvRmssdMs?.let { "%.0f".format(it) } ?: "--",
                unit = "ms",
                status = numericStatus(snapshot.hrvRmssdMs, 20f, 90f),
                classifierContribution = "Recovery / arousal context",
                availability = sensorSdk.message,
                permissionState = sensorSdk.permissionState,
                supportState = sensorSdk.supportState,
            ),
            MetricReading(
                metricId = "accelerometer",
                title = "Accelerometer",
                provider = MetricProvider.AndroidSensors,
                serviceName = "Android Sensor Manager",
                sourceKey = "Sensor.TYPE_ACCELEROMETER",
                kind = MetricKind.Raw,
                value = snapshot.accelerometerMagnitudeG?.let { "%.3f".format(it) } ?: "--",
                unit = "g",
                status = numericStatus(snapshot.accelerometerMagnitudeG, 0.02f, 0.8f),
                classifierContribution = "Stillness and movement intensity",
                availability = androidSensors.message,
                permissionState = androidSensors.permissionState,
                supportState = androidSensors.supportState,
            ),
            MetricReading(
                metricId = "posture",
                title = "Posture/orientation",
                provider = MetricProvider.AndroidSensors,
                serviceName = "Android Sensor Manager",
                sourceKey = "Sensor.TYPE_GYROSCOPE (derived)",
                kind = MetricKind.Derived,
                value = snapshot.posture ?: "--",
                unit = "",
                status = MetricStatus.Normal,
                classifierContribution = "Sleep vs awake posture context",
                availability = androidSensors.message,
                permissionState = androidSensors.permissionState,
                supportState = androidSensors.supportState,
            ),
            MetricReading(
                metricId = "speed",
                title = "Speed",
                provider = MetricProvider.HealthServices,
                serviceName = "ExerciseClient",
                sourceKey = "DataType.SPEED",
                kind = MetricKind.Raw,
                value = snapshot.speedMs?.let { "%.1f".format(it) } ?: "--",
                unit = "m/s",
                status = numericStatus(snapshot.speedMs, 0.1f, 2.2f),
                classifierContribution = "Walking vs Active",
                availability = healthServices.message,
                permissionState = healthServices.permissionState,
                supportState = healthServices.supportState,
            ),
            MetricReading(
                metricId = "cadence",
                title = "Cadence",
                provider = MetricProvider.HealthServices,
                serviceName = "ExerciseClient",
                sourceKey = "DataType.STEPS_PER_MINUTE",
                kind = MetricKind.Raw,
                value = snapshot.cadenceSpm?.let { "%.0f".format(it) } ?: "--",
                unit = "spm",
                status = numericStatus(snapshot.cadenceSpm, 10f, 130f),
                classifierContribution = "Walking/Active cadence match",
                availability = healthServices.message,
                permissionState = healthServices.permissionState,
                supportState = healthServices.supportState,
            ),
            MetricReading(
                metricId = "skin_temp",
                title = "Skin temperature",
                provider = MetricProvider.SensorSdk,
                serviceName = "Sensor SDK",
                sourceKey = "SKIN_TEMPERATURE_ON_DEMAND",
                kind = MetricKind.Raw,
                value = snapshot.skinTempC?.let { "%.1f".format(it) } ?: "--",
                unit = "C",
                status = numericStatus(snapshot.skinTempC, 35.8f, 37.5f),
                classifierContribution = "Low-weight context",
                availability = sensorSdk.message,
                permissionState = sensorSdk.permissionState,
                supportState = sensorSdk.supportState,
            ),
            MetricReading(
                metricId = "spo2",
                title = "SpO2",
                provider = MetricProvider.SensorSdk,
                serviceName = "Sensor SDK",
                sourceKey = "SPO2_ON_DEMAND",
                kind = MetricKind.Raw,
                value = snapshot.spo2Pct?.toString() ?: "--",
                unit = "%",
                status = numericStatus(snapshot.spo2Pct?.toFloat(), 93f, 100f),
                classifierContribution = "Low-weight context",
                availability = sensorSdk.message,
                permissionState = sensorSdk.permissionState,
                supportState = sensorSdk.supportState,
            ),
            MetricReading(
                metricId = "elevation",
                title = "Elevation change",
                provider = MetricProvider.HealthServices,
                serviceName = "ExerciseClient",
                sourceKey = "DataType.ABSOLUTE_ELEVATION (derived m/min)",
                kind = MetricKind.Derived,
                value = snapshot.elevationChangeMpm?.let { "%.1f".format(it) } ?: "--",
                unit = "m/min",
                status = numericStatus(snapshot.elevationChangeMpm, 0f, 15f),
                classifierContribution = "Terrain/exertion context",
                availability = healthServices.message,
                permissionState = healthServices.permissionState,
                supportState = healthServices.supportState,
            ),
            MetricReading(
                metricId = "platform_state",
                title = "Platform state",
                provider = MetricProvider.HealthServices,
                serviceName = "PassiveMonitoringClient",
                sourceKey = "UserActivityState",
                kind = MetricKind.PlatformState,
                value = snapshot.platformUserState ?: "UNKNOWN",
                status = MetricStatus.Normal,
                classifierContribution = "Platform context",
                availability = healthServices.message,
                permissionState = healthServices.permissionState,
                supportState = healthServices.supportState,
            ),
            MetricReading(
                metricId = "classifier",
                title = "Classifier summary",
                provider = MetricProvider.Classifier,
                serviceName = "Vigil classifier",
                sourceKey = "Weighted threshold scoring",
                kind = MetricKind.Derived,
                value = snapshot.classifiedState?.name ?: "Unknown",
                unit = snapshot.modeAlignment?.name ?: "",
                status = when {
                    snapshot.alertReason != null -> MetricStatus.Warning
                    else -> MetricStatus.Normal
                },
                trend = "Confidence ${snapshot.confidence?.let { "%.2f".format(it) } ?: "--"}",
                classifierContribution = snapshot.reasons.joinToString(" • "),
                availability = "Available",
                permissionState = PermissionState.NotRequired,
                supportState = SupportState.Supported,
            ),
        )
    }

    private fun numericStatus(value: Float?, warnAt: Float, highAt: Float): MetricStatus {
        val v = value ?: return MetricStatus.Unavailable
        return when {
            v > highAt -> MetricStatus.Critical
            v > warnAt -> MetricStatus.Warning
            else -> MetricStatus.Normal
        }
    }
}
